#+TITLE: Wim's GNU Emacs Configuration
#+AUTHOR: Wim Alsemgeest
#+DESCRIPTION: Personal Emacs configuration.
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Emacs configuration.
** Package manager
#+begin_src emacs-lisp

  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
			   ("org" . "https://orgmode.org/elpa/")
			   ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  
#+end_src

** Install use-package
Website of [[https://github.com/jwiegley/use-package#installing-use-package][use-package]]
#+begin_src emacs-lisp

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)

  #+end_src

** General settings
Don show the splash screen
Flash when the bell rings
Turn off the toolbar
Turn off the scrollbar
Turn off the menubar
Give some breathing room

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)       ;; Don't show the splash screen
  (setq visible-bell t)                  ;; Flash when the bell rings
  (tool-bar-mode -1)                     ;; Turn off the toolbar
  (scroll-bar-mode -1)                   ;; Turn off the scrollbar
  ;; (menu-bar-mode -1)                     ;; Turn off the menubar
  (set-fringe-mode 10)

#+end_src


** Make ESC quit prompts
#+begin_src emacs-lisp

  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

#+end_src

** Set line and column numbers
Show linenummers
Show column nummer mode
Disable line numbers for some modes
#+begin_src emacs-lisp

  (global-display-line-numbers-mode 1)
  (setq column-number-mode t)
  (dolist (mode '(org-mode-hook
		  term-mode-hook
		  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
  
#+end_src

** Remember the last edited files, history minibuffer and last cursor position
#+begin_src emacs-lisp

  (recentf-mode 1)                       ;; Remember the last edited files
  (setq history-length 25)               ;; Remember the last minibuffer prompts
  (savehist-mode 1)                      ;; Enable save-history mode
  (save-place-mode 1)                    ;; Remember and restore de last cursor position

#+end_src
** Prevent UI dialog for prompts
#+begin_src emacs-lisp

  (setq use-dialog-box nil)              ;; Prevent using UI dialog for prompts

#+end_src

** Revert buffers when they are externaly changed
#+begin_src emacs-lisp

  (global-auto-revert-mode 1)            ;; Revert buffers when file is changed
  (setq global-auto-revert-non-file-buffers t)  ;; Revert Dired and other buffers
  
#+end_src

** Move customization variable to a separate file and load it
#+begin_src emacs-lisp

  (setq custom-file (locate-user-emacs-file "custom-vars.el"))
  (load custom-file 'noerror 'nomessage)
  
#+end_src


** Set fontface for Org and other modes
Set the main type face font to Source Code Pro.
Set the proportionately spaced type face to URW Bookman.
Set the fixed-type face font to Source Code Pro.
#+begin_src emacs-lisp

  (set-face-attribute 'default nil :family "Source Code Pro" :height 110)
  (set-face-attribute 'variable-pitch nil :family "URW Bookman" :height 110)
  (set-face-attribute 'fixed-pitch nil :family "Source Code Pro" :height 110)
  
#+end_src

** Set tranparency
#+begin_src
(set-frame-parameter (selected-frame) 'alpha '(90 . 90))
(add-to-list 'default-frame-alist '(alpha . (90 . 90)))

#+end_src

** Set windows maximized
#+begin_src emacs-lisp

  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
  
#+end_src

** Setting the theme in Emacs
Theme configuration before loading the theme
Link to website modus-themes https://protesilaos.com/emacs/
#+begin_src emacs-lisp

  (use-package modus-themes
    :ensure t
    :config
    ;; Add all your customizations prior to loading the themes
    (setq modus-themes-italic-constructs t
	  modus-themes-bold-constructs t
	  modus-themes-mixed-fonts t

	  modus-themes-org-blocks "grey-background"
	  )

    (setq modus-themes-headings
	  '((1 . (variable-pitch 1.8))
	    (2 . (variable-pitch 1.6))
	    (3 . (variable-pitch 1.4))
	    (4 . (variable-pitch 1.2))
	    (5 . (variable-pitch 1.0))
	    ))
  

    ;; Maybe define some palette overrides, such as by using our presets
    ;; (setq modus-themes-common-palette-overrides
    ;;	modus-themes-preset-overrides-intense)
    )

  ;; ----- Load the theme and define a key to toggle dark and light ----------------------------------
  (load-theme 'modus-vivendi-tinted t)
  (define-key global-map (kbd "<f5>") #'modus-themes-toggle)

#+end_src

** Install which-key
[[https://github.com/justbur/emacs-which-key][which-key]] on github.com

#+begin_src emacs-lisp

  (use-package which-key
    :init (which-key-mode)
    :diminish which-key-mode
    :config
    (setq which-key-idle-delay 0.3)
    (which-key-setup-side-window-right))
  
#+end_src

** Rainbow Delimiters
#+begin_src emacs-lisp

  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
  
#+end_src

** Helpful
[[https://github.com/Wilfred/helpful][Helpful package]] on github.com

#+begin_src emacs-lisp

  (use-package helpful)
    (global-set-key (kbd "C-h f") #'helpful-callable)
    (global-set-key (kbd "C-h v") #'helpful-variable)
    (global-set-key (kbd "C-h k") #'helpful-key)
    (global-set-key (kbd "C-h x") #'helppul-command)
  
#+end_src

** Doom-modeline
[[https://github.com/seagle0128/doom-modeline][Doom-modeline package]] on github.com
[[https://github.com/ttys3/emacs-doom-themes][Doom-themes package]] on github.com

#+begin_src emacs-lisp
  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :custom ((doom-modeline-height 15)))

#+end_src

** Rainbow-mode for color hightlighting
[[https://github.com/emacsmirror/rainbow-mode/blob/master/rainbow-mode.el][Rainbow-mode package]] on github.com

#+begin_src emacs-lisp

  (use-package rainbow-mode
    :ensure t)
  
#+end_src

** Auto completion with ivy
[[https://github.com/abo-abo/swiper][Ivy, swiper and counsel]] can be found on github.com

#+begin_src emacs-lisp
  (use-package ivy
  :diminish
  :bind (("C-s" . swiper)
	 :map ivy-minibuffer-map
	 ("TAB" . ivy-alt-done)
	 ("C-l" . ivy-alt-done)
	 ("C-j" . ivy-next-line)
	 ("C-k" . ivy-previous-line)
	 :map ivy-switch-buffer-map
	 ("C-k" . ivy-previous-line)
	 ("C-l" . ivy-done)
	 ("C-d" . ivy-switch-buffer-kill)
	 :map ivy-reverse-i-search-map
	 ("C-k" . ivy-previous-line)
	 ("C-d" . ivy-reverse-i-search-kill))
  :config
  (ivy-mode 1))
#+end_src
  
** Vertico for autocompletion
[[https://github.com/minad/vertico][Vertico package]] on github.com


  (use-package vertico
    :ensure t
    :config
    (vertico-mode))
  

** orderless completion style
[[https://github.com/oantolin/orderless][Orderless package]] on github.com
#+begin_src emacs-lisp

    (use-package orderless
      :ensure t
      :config
      (setq completion-styles '(orderless)))
  
#+end_src

** marginalia
[[https://github.com/minad/marginalia][Marginalia package]] on github.com

#+begin_src emacs-lisp

  (use-package marginalia
    :ensure t
    :config
    (marginalia-mode))
  
#+end_src

** LSP mode
[[https://emacs-lsp.github.io/lsp-mode/][LSP-mode package]] webpage

#+begin_src emacs-lisp

    (use-package lsp-mode
       :ensure
       :commands lsp
       :custom
       (setq lsp-keymap-prefix "C-c l")
       ;; what to use when checking on-save. "check" is default, I prefer clippy
       (lsp-rust-analyzer-cargo-watch-command "clippy")
       (lsp-eldoc-render-all t)
       (lsp-idle-delay 0.6)
       ;; enable / disable the hints as you prefer
       (lsp-rust-analyzer-server-display-inlay-hints t)
       (lsp-rust-analyzer-display-lifetime-elision-hints-enable "skip_trivial")
       (lsp-rust-analyzer-display-chaining-hints t)
       (lsp-rust-analyzer-display-lifetime-elision-hints-use-parameter-names nil)
       (lsp-rust-analyzer-display-closure-return-type-hints t)
       (lsp-rust-analyzer-display-parameter-hints nil)
       (lsp-rust-analyzer-display-reborrow-hints nil)
       :config
       (add-hook 'lsp-mode-hook 'lsp-ui-mode))

    (use-package lsp-ui
      :ensure
      :commands lsp-ui-mode
      :custom
      (lsp-ui-peek-always-show t)
      (lsp-ui-sideline-show-hover t)
      (lsp-ui-doc-enable nil))

#+end_src

** Rustic
[[https://github.com/brotzeit/rustic][Rustic package]] on github.com

#+begin_src emacs-lisp

  (use-package rustic
    :ensure
    :bind (:map rustic-mode-map
		("M-j" . lsp-ui-imenu)
		("M-?" . lsp-find-references)
		("C-c C-c l" . flycheck-list-errors)
		("C-c C-c a" . lsp-execute-code-action)
		("C-c C-c r" . lsp-rename)
		("C-c C-c q" . lsp-workspace-restart)
		("C-c C-c Q" . lsp-workspace-shutdown)
		("C-c C-c s" . lsp-rust-analyzer-status))
    :config
    ;; Uncomment for less flashiness
    ;; (setq lsp-eldoc-hook nil)
    ;; (setq lsp-enable-symbol-highlighting nil)
    ;; (setq lsp-signature-auto-activate nil)

    ;; comment to disable rustfmt on save
    (setq rustic-format-on-save t))

#+end_src

** Company

#+begin_src emacs-lisp

	  (use-package company
	      :ensure
	      :custom
	      (company-idle-delay 0.5) ;; How long to wait until popup
	      ;; (company-begin-commands nil) ;; Uncomment to disable
	      :bind
	      (:map company-active-map
		    ("C-n" . company-select-next)
		    ("C-p" . company-select-previous)
		    ("M-<" . company-select-first)
		    ("M->" . company-select-last))
	      (:map company-mode-map
		    ("<tab>" . tab-indent-or-complete)
		    ("TAB" . tab-indent-or-complete)))
  
	  (defun company-yasnippet-or-completion ()
	  (interactive)
	  (or (do-yas-expand)
	      (company-complete-common)))

	(defun check-expansion ()
	  (save-excursion
	    (if (looking-at "\\_>") t
	      (backward-char 1)
	      (if (looking-at "\\.") t
		(backward-char 1)
		(if (looking-at "::") t nil)))))

	(defun do-yas-expand ()
	  (let ((yas/fallback-behavior 'return-nil))
	    (yas/expand)))

	(defun tab-indent-or-complete ()
	  (interactive)
	  (if (minibufferp)
	      (minibuffer-complete)
	    (if (or (not yas/minor-mode)
		    (null (do-yas-expand)))
		(if (check-expansion)
		    (company-complete-common)
		  (indent-for-tab-command)))))
#+end_src

** Yasnippet
#+begin_src emacs-lisp

  (use-package yasnippet
    :ensure
    :config
    (yas-reload-all)
    (add-hook 'prog-mode-hook 'yas-minor-mode)
    (add-hook 'text-mode-hook 'yas-minor-mode))
  
#+end_src

** Flycheck
#+begin_src emacs-lisp

  (use-package flycheck :ensure)

#+end_src

** Projectile
#+begin_src emacs-lisp

  (use-package projectile
      :diminish projectile-mode
      :config (projectile-mode)
      :custom ((projectile-completion-system 'ivy))
      :bind-keymap
      ("C-c p" . projectile-command-map)
      :init
      (when (file-directory-p "~/project/code")
	(setq projectile-project-search-path '("~/project/code")))
      (setq projectile-switch-project-action #'projectile-dired))

  (use-package counsel-projectile
    :config (counsel-projectile-mode))
  
#+end_src

** Magit
#+begin_src emacs-lisp
  (use-package magit
    :commands (magit-status magit-get-current-branch)
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))
  
#+end_src

** Rust mode
[[https://github.com/rust-lang/rust-mode][Rust-mode package]] on github.com

#+begin_src emacs-lisp

#+end_src
