#+TITLE: Wim's Emacs configuratie
#+AUTHOR: Wim Alsemgeest


* Package management
** Stel package.el in om met MELPA te werken.

** Algemene instellingen
- Onderdruk start bericht
- Flits als de bel gaat.
- Zet wat modes uit
  + Menu bar mode (deze blijft nog even aan zolang ik nog zoekende ben).
  + Tool bar mode
  + scroll bar mode
- Laat geen UI dialoog schermen zien
- Automatisch buffers bij werken als ze extern gewijzigd worden.  
#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (setq visible-bell t)
  ;; (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (setq use-dialog-box nil)
  (global-auto-revert-mode 1)
#+end_src

** Regelnummers
Laat regelnummer in alle buffers zien.
#+begin_src emacs-lisp
  (global-display-line-numbers-mode 1)
#+end_src

** Recente bestanden onthouden
Met het commando (recent-open-files) krijgen we een lijst met de laatst gebruikte bestanden. Kies het bestand door het nummer te kiezen.
*** TODO Toets combinatie voor recent-open-files maken.
#+begin_src emacs-lisp
  (recentf-mode 1)
#+end_src

** Mini-buffer commando historie
We gebruiken de mini-buffer heel veel in Emacs. Handig om door de historie te kunnen wandelen.
Als de mode aan staat kunnen we met ~M-n~ (next-history-element) en ~M-p~ (previous-history-element) gebruiken om door de lijst te wandelen.
#+begin_src emacs-lisp
  (setq history-length 50)
  (savehist-mode 1)
#+end_src

** Herhinder de laatste plek waar we bewerking deden
#+begin_src emacs-lisp
  (save-place-mode 1)
#+end_src

** Verplaats de locatie van "custom file"
Emacs zal soms zelf dingen toevoegen aan de "init.el". Dat is niet wenselijk. We kunnen deze gegevens opslaan in een apart bestand.
#+begin_src emacs-lisp
  (setq custom-file (locate-user-emacs-file "custom-vars.el"))
  (load custom-file 'noerror 'nomessage)
#+end_src

** Instellen van een thema
We gebruiken de nieuwe ingebouwde modus-vivendi
#+begin_src emacs-lisp
  (load-theme 'modus-vivendi t)
#+end_src
